function update_plot_fcn(handle, event, daystruct)


data = guidata(handle);

delete(findobj('type','uipanel'))
    
    
plot_control = uipanel('Parent', data.mainfig,...
             'tag','plot_control',...
             'units', 'normalized',...
             'ShadowColor',[1 1 0.7],...
             'BackgroundColor',[1 1 0.7],...
             'position',   [0.02 0.25 (1 - 2*0.02) 0.5]);        
         
startday_nr = get(data.startdate_popup, 'value');
endday_nr = get(data.enddate_popup, 'value');

day_panel_number = (endday_nr - startday_nr) + 1;

x_dis_day_pan = 0;
y_dis_day_pan = 0;
x_size_day_pan = (1-(2*x_dis_day_pan))/day_panel_number ;
y_size_day_pan = 1 - 2*y_dis_day_pan;

x_pos_daytime_pan = 0;
% y_pos_midnight_pan = 0.75;
y_pos_morning_pan = 0.67;
y_pos_midday_pan = 0.34;
y_pos_evening_pan = 0;
x_size_daytime_pan = 1;
y_size_daytime_pan = 0.33;

degree_symbol = sprintf('%c', char(176));

temp_text_size = 0.7;
prec_text_size = 0.8;

for pan_idx = startday_nr : endday_nr
    
    day_panel_control = uipanel('Parent', plot_control,...
                            'units', 'normalized',...
                            'Title', daystruct(pan_idx).date,...
                            'TitlePosition', 'centertop',...
                            'FontUnits','normalized',...
                            'FontSize',0.05,...
                            'FontWeight', 'bold',...
                            'ShadowColor',[1 1 0.7],...
                            'BackgroundColor',[1 1 0.7],...
                            'position',[x_dis_day_pan + (pan_idx-startday_nr)*(x_size_day_pan),...
                            y_dis_day_pan, x_size_day_pan, y_size_day_pan]);
                        
  
   morning_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Morning:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize',0.15,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_morning_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);
    

                        
if isa(daystruct(pan_idx).temperature.morning,'double') == 1
    
     morning_NA_text_control = uicontrol('Parent', morning_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.3,...
                            'position',   [0.05 0.2 0.9 0.6],...
                            'BackgroundColor', [1 1 0.7],...
                            'string', 'weatherdata n.a.');

elseif isa(daystruct(pan_idx).temperature.morning,'double') == 0
                        
    morning_picture_weather = axes('Parent', morning_panel_control,...
                            'Units','normalized',...
                            'Box','Off',...
                            'Position',[0 0.4 0.5 0.5]);          
                            axes(morning_picture_weather);
                            image(daystruct(pan_idx).picture.morning);
                            axis image  
                            axis off
                
    morning_temp_text_control = uicontrol('Parent', morning_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize', temp_text_size,...
                            'position',   [0.4 0.4 0.6 0.5],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat(daystruct(pan_idx).temperature.morning.value,...
                            degree_symbol, 'C'));
                           
   morning_precipitation_text_control = uicontrol('Parent', morning_panel_control,...
                            'style','text',...
                            'FontUnits','normalized',...
                            'FontSize',prec_text_size,...
                            'units', 'normalized',...
                            'position',   [0 0.16 1 0.2],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat('precipitation: ',...
                            daystruct(pan_idx).precipitation.morning.value, char(12),...
                            daystruct(pan_idx).precipitation.morning.unit));
end

%------midday-panel-----------------------------------------

midday_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Midday:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize',0.15,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_midday_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);

if isa(daystruct(pan_idx).temperature.midday,'double') == 1
    
     midday_NA_text_control = uicontrol('Parent', midday_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.3,...
                            'position',   [0.05 0.2 0.9 0.6],...
                            'BackgroundColor', [1 1 0.7],...
                            'string', 'weatherdata n.a.');


elseif isa(daystruct(pan_idx).temperature.midday,'double') == 0


                        
    midday_picture_weather = axes('Parent', midday_panel_control,...
                            'Units','normalized',...
                            'Box','Off',...
                            'Position',[0 0.4 0.5 0.5]);          
                            axes(midday_picture_weather);
                            image(daystruct(pan_idx).picture.midday);
                            axis image  
                            axis off
                
    midday_temp_text_control = uicontrol('Parent', midday_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize', temp_text_size,...
                            'position',   [0.4 0.4 0.6 0.5],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat(daystruct(pan_idx).temperature.midday.value,...
                            degree_symbol, 'C'));
                           
   midday_precipitation_text_control = uicontrol('Parent', midday_panel_control,...
                            'style','text',...
                            'FontUnits','normalized',...
                            'FontSize',prec_text_size,...
                            'units', 'normalized',...
                            'position',   [0 0.16 1 0.2],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat('precipitation: ',...
                            daystruct(pan_idx).precipitation.midday.value, char(12),...
                            daystruct(pan_idx).precipitation.midday.unit)); 
end

%---------evening-panel-----------------------------------------------------

evening_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Evening:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize',0.15,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_evening_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);

if isa(daystruct(pan_idx).temperature.evening,'double') == 1
    
     morning_NA_text_control = uicontrol('Parent', evening_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.3,...
                            'position',   [0.05 0.2 0.9 0.6],...
                            'BackgroundColor', [1 1 0.7],...
                            'string', 'weatherdata n.a.');

elseif isa(daystruct(pan_idx).temperature.evening,'double') == 0
    
                        
    evening_picture_weather = axes('Parent', evening_panel_control,...
                            'Units','normalized',...
                            'Box','Off',...
                            'Position',[0 0.4 0.5 0.5]);          
                            axes(evening_picture_weather);
                            image(daystruct(pan_idx).picture.evening);
                            axis image  
                            axis off

    evening_temp_text_control = uicontrol('Parent', evening_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',temp_text_size,...
                            'position',   [0.4 0.4 0.6 0.5],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat(daystruct(pan_idx).temperature.evening.value,...
                            degree_symbol, 'C'));
                           
   evening_precipitation_text_control = uicontrol('Parent', evening_panel_control,...
                            'style','text',...
                            'FontUnits','normalized',...
                            'FontSize',prec_text_size,...
                            'units', 'normalized',...
                            'position',   [0 0.16 1 0.2],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat('precipitation: ',...
                            daystruct(pan_idx).precipitation.evening.value,...
                            char(12), daystruct(pan_idx).precipitation.evening.unit)); 

end
end

end