function update_plot_fcn(handle, event, daystruct)
%UPDATE_PLOT_FCN plots the weatherdata for the predefined day interval

%   UPDATE_PLOT_FCN(handle, event, daystruct) checks the startday and endday 
%   appointed by the user. It calculates the day intervall and plots the
%   weatherinformation temperature, percipitation and a picture of the
%   forecast weather for the daytimes morning, midday and evening if they are available.
%   The button 'update weatherdata' is enable while this function is busy.
%
%   This function only works in combination with the script
%   weather_forecast_main_script and is conducted after pressing the button 
%   'show weatherforecast'

% Copyright 2014 Laura Hartog, Franz Wichert

data = guidata(handle);

delete(findobj('type','uipanel'))
    
% create a panel for the weatherdata   
plot_control = uipanel('Parent', data.mainfig,...
             'tag','plot_control',...
             'units', 'normalized',...
             'ShadowColor',[1 1 0.7],...
             'BackgroundColor',[1 1 0.7],...
             'position',   [0.02 0.1 (1 - 2*0.02) 0.65]);        
 
% get the start- and enddate chosen by the user          
startday_nr = get(data.startdate_popup, 'value');
endday_nr = get(data.enddate_popup, 'value');

% variable day_panel_number contains the chosen day interval
day_panel_number = (endday_nr - startday_nr) + 1;

%determine the sizes of the panels for each date dependend on
%day_panel-number
x_dis_day_pan = 0;
y_dis_day_pan = 0;
x_size_day_pan = (1-(2*x_dis_day_pan))/day_panel_number ;
y_size_day_pan = 1 - 2*y_dis_day_pan;

%determine the sizes of the panels for the infomrations of morning, midday 
%end evening for each day panel

x_pos_daytime_pan = 0;
x_size_daytime_pan = 1;

% if only one day is chosen, decrease x-size of daypanel
if day_panel_number < 2;
    x_pos_daytime_pan = 0.25;
    x_size_daytime_pan = 0.5;
end

y_pos_morning_pan = 0.67;
y_pos_midday_pan = 0.34;
y_pos_evening_pan = 0;
y_size_daytime_pan = 0.33;

%variable degree_symbol contains the degree symbol 
degree_symbol = sprintf('%c', char(176));

%determine the sizes and positions of the below used texts and pictures
date_text_size = 0.15;

temp_text_size = 0.6;

%decrease temp_text_size if day_panel_number < 5
if day_panel_number > 5;
    
    temp_text_size = 0.5;

end

temp_pos = [0.4 0.4 0.6 0.5];

prec_text_size = 0.8;
prec_pos = [0 0.16 1 0.2];

NA_text_size = 0.3;
NA_text_pos = [0.05 0.15 0.9 0.6];

pic_pos = [0 0.4 0.5 0.5];

%in order to prevent the multible execution of this function until it 
%is done the button 'show weatherforecast' is not enable
set(data.weatherupdate_push, 'enable', 'off');

% for-loop that creates a panel for each day of the chosen day interval
% using the pan_idx which starts and ends with the preassigned days.
% it creates a morning-, midday- and eveningpanel for each day which
% contains a picture of the forecast weather, the temperature and the
% percipitation
for pan_idx = startday_nr : endday_nr
    % create the panel for each day with the fixed sizes
    day_panel_control = uipanel('Parent', plot_control,...
                            'units', 'normalized',...
                            'Title', daystruct(pan_idx).date,...
                            'TitlePosition', 'centertop',...
                            'FontUnits','normalized',...
                            'FontSize', 0.05,...
                            'FontWeight', 'bold',...
                            'ShadowColor', [1 1 0.7],...
                            'BackgroundColor', [1 1 0.7],...
                            'position',[x_dis_day_pan + (pan_idx-startday_nr)*(x_size_day_pan),...
                            y_dis_day_pan, x_size_day_pan, y_size_day_pan]);
                        
   %create he panel of the first daytime with the fixed sizes
   morning_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Morning:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize', date_text_size,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_morning_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);
    

   % check if the weatherdata of the current daytime are available                   
   if isa(daystruct(pan_idx).temperature.morning,'double') == 1
       % current weatherdata is not available:
       % create the information: 'weatherdata n.a.'
       morning_NA_text_control = uicontrol('Parent', morning_panel_control,...
                                'style','text',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'FontSize',NA_text_size,...
                                'position', NA_text_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string', 'weatherdata n.a.');

   elseif isa(daystruct(pan_idx).temperature.morning,'double') == 0
       % current weatherdata is available:
       
       % plot the picture with the predicited weather for the currentdaytime

       morning_picture_weather = axes('Parent', morning_panel_control,...
                                'Units','normalized',...
                                'Box','Off',...
                                'Position', pic_pos);          
                                axes(morning_picture_weather);
                                image(daystruct(pan_idx).picture.morning);
                                axis image
                                axis off
                                
       % print the predicited temperature for the current daytime
       morning_temp_text_control = uicontrol('Parent', morning_panel_control,...
                                'style','text',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'FontSize', temp_text_size,...
                                'position',   temp_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string',  horzcat(daystruct(pan_idx).temperature.morning.value,...
                                degree_symbol, 'C'));
                            
       % print the predicited precipitaion for the current daytime
       morning_precipitation_text_control = uicontrol('Parent', morning_panel_control,...
                                'style','text',...
                                'FontUnits','normalized',...
                                'FontSize',prec_text_size,...
                                'units', 'normalized',...
                                'position',   prec_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string',  horzcat('precipitation: ',...
                                daystruct(pan_idx).precipitation.morning.value, char(12),...
                                daystruct(pan_idx).precipitation.morning.unit));
   end
   
% repetition of the procedure of morning-panel for the next daytimes
%------midday-panel-----------------------------------------

   midday_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Midday:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize', date_text_size,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_midday_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);

   if isa(daystruct(pan_idx).temperature.midday,'double') == 1
    
       midday_NA_text_control = uicontrol('Parent', midday_panel_control,...
                                'style','text',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'FontSize',NA_text_size,...
                                'position',   NA_text_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string', 'weatherdata n.a.');


   elseif isa(daystruct(pan_idx).temperature.midday,'double') == 0



       midday_picture_weather = axes('Parent', midday_panel_control,...
                                'Units','normalized',...
                                'Box','Off',...
                                'Position',pic_pos);          
                                axes(midday_picture_weather);
                                image(daystruct(pan_idx).picture.midday);
                                axis image  
                                axis off

       midday_temp_text_control = uicontrol('Parent', midday_panel_control,...
                                'style','text',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'FontSize', temp_text_size,...
                                'position',   temp_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string',  horzcat(daystruct(pan_idx).temperature.midday.value,...
                                degree_symbol, 'C'));

       midday_precipitation_text_control = uicontrol('Parent', midday_panel_control,...
                                'style','text',...
                                'FontUnits','normalized',...
                                'FontSize',prec_text_size,...
                                'units', 'normalized',...
                                'position',   prec_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string',  horzcat('precipitation: ',...
                                daystruct(pan_idx).precipitation.midday.value, char(12),...
                                daystruct(pan_idx).precipitation.midday.unit)); 
    end

%---------evening-panel-----------------------------------------------------

    evening_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Evening:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize', date_text_size,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_evening_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);

    if isa(daystruct(pan_idx).temperature.evening,'double') == 1
    
        evening_NA_text_control = uicontrol('Parent', evening_panel_control,...
                                'style','text',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'FontSize',NA_text_size,...
                                'position', NA_text_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string', 'weatherdata n.a.');

    elseif isa(daystruct(pan_idx).temperature.evening,'double') == 0


        evening_picture_weather = axes('Parent', evening_panel_control,...
                                'Units','normalized',...
                                'Box','Off',...
                                'Position',pic_pos);          
                                axes(evening_picture_weather);
                                image(daystruct(pan_idx).picture.evening);
                                axis image  
                                axis off

        evening_temp_text_control = uicontrol('Parent', evening_panel_control,...
                                'style','text',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'FontSize',temp_text_size,...
                                'position',   temp_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string',  horzcat(daystruct(pan_idx).temperature.evening.value,...
                                degree_symbol, 'C'));

       evening_precipitation_text_control = uicontrol('Parent', evening_panel_control,...
                                'style','text',...
                                'FontUnits','normalized',...
                                'FontSize',prec_text_size,...
                                'units', 'normalized',...
                                'position',   prec_pos,...
                                'BackgroundColor', [1 1 0.7],...
                                'string',  horzcat('precipitation: ',...
                                daystruct(pan_idx).precipitation.evening.value,...
                                char(12), daystruct(pan_idx).precipitation.evening.unit)); 

    end
end
% button 'show weatherforecast' is enable again
set(data.weatherupdate_push, 'enable', 'on')

end