% Skript mit welchem eine xml-Datei von der Seite 
% http://api.met.no/weatherapi/locationforecast/1.8/?lat=53.143889;lon=8.213889
% heruntergeladen, verarbeitet und geplottet werden kann.
%
% Author: L. Hartog, F. Wichert (c) IHA @ Jade Hochschule applied licence see EOF 
% Version History:
% Ver. 0.01 initial create (empty) 18-Apr-2014 			 Initials (eg. JB)

clear;
close all;
clc;

daystruct = weather_data_reprocessing();

hfig = figure();

set(hfig,'units','normalized',...
         'tag','mainfig',...
         'position', [0 0 1 1],...
         'ToolBar','none',...
         'Color',[1 1 0.7],...
         'MenuBar','none');


% -----------------Einbinden der Uberschrift ----------------------------

title_text_control = uicontrol(hfig,'style','text',...
                                'units', 'normalized',...
                                'position',   [0.35 0.87 0.3 0.1],...
                                'string', 'Weather Forecast Oldenburg',...
                                'FontUnits','normalized',...
                                'FontSize',0.45,...
                                'BackgroundColor', [1 1 0.7]);                     

%--- Einbinden des Startdatums sowie Enddatums der Wettervorhersage-------
                            
x_pos_date = 0.02;
y_pos_date = 0.8;
x_size_date = 0.18;
y_size_date = 0.03;
x_distance_date = 0.01;
y_distance_date = 0.01;
date_text_size = 0.9;
date_popup_size = 0.7;

startdate_text_control = uicontrol(hfig,'style', 'text',...
                                'units','normalized',...
                                'BackgroundColor',[1 0.8 0.4],...
                                'FontUnits','normalized',...
                                'Fontsize', date_text_size,...
                                'position',[x_pos_date (y_pos_date + (y_size_date + y_distance_date)) x_size_date y_size_date],...
                                'string','startdate:');              


enddate_text_control = uicontrol(hfig,'style', 'text',...
                                'units','normalized',...
                                'FontUnits','normalized',...
                                'Fontsize', date_text_size,...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_date + (x_size_date + x_distance_date) y_pos_date + (y_size_date + y_distance_date), x_size_date y_size_date],...
                                'string','enddate:'); 
                            
startdate_popup_control = uicontrol(hfig,'style', 'popupmenu',...
                                'tag','startdate_popup',...
                                'units','normalized',...
                                'FontUnits','normalized',...
                                'Fontsize', date_popup_size,...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_date y_pos_date x_size_date y_size_date],...
                                'string',{daystruct(1).date,...
                                daystruct(2).date, daystruct(3).date, daystruct(4).date...
                                daystruct(5).date, daystruct(6).date, daystruct(7).date},...
                                 'callback',@Error_window_fcn);
                           
enddate_popup_control = uicontrol(hfig, 'style', 'popupmenu',...
                                'tag','enddate_popup',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'Fontsize', date_popup_size,...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position', [x_pos_date + (x_size_date + x_distance_date) y_pos_date x_size_date y_size_date],...
                                'string', {daystruct(1).date,...
                                daystruct(2).date, daystruct(3).date,daystruct(4).date...
                                daystruct(5).date, daystruct(6).date,daystruct(7).date},...
                                'callback',@Error_window_fcn);


%-----------------Einbinden Update-Button--------------------

weatherupdate_control = uicontrol(hfig,'style', 'pushbutton',...
                                'tag','weatherupdate_push',...
                                'units','normalized',...
                                'position',[0.7 0.79 0.28 0.08],...
                                'BackgroundColor',[1 0.8 0.4],...
                                'string','update weatherdata',...
                                'callback', {@update_plot_fcn, daystruct});


                            
                            
                            
                            

data = guihandles(hfig);
guidata(hfig, data);

    
                        
                            
                            
%--------------------Licence ---------------------------------------------
% Copyright (c) <2014> L. Hartog, F. Wichert
% Institute for Hearing Technology and Audiology
% Jade University of Applied Sciences 
% Permission is hereby granted, free of charge, to any person obtaining 
% a copy of this software and associated documentation files 
% (the "Software"), to deal in the Software without restriction, including 
% without limitation the rights to use, copy, modify, merge, publish, 
% distribute, sublicense, and/or sell copies of the Software, and to
% permit persons to whom the Software is furnished to do so, subject
% to the following conditions:
% The above copyright notice and this permission notice shall be included 
% in all copies or substantial portions of the Software.
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
% EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
% OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
% IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
% CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
% TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
% SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.