% Skript mit welchem eine xml-Datei von der Seite 
% http://api.met.no/weatherapi/locationforecast/1.8/?lat=53.143889;lon=8.213889
% heruntergeladen, verarbeitet und geplottet werden kann.
%
% Author: L. Hartog, F. Wichert (c) IHA @ Jade Hochschule applied licence see EOF 
% Version History:
% Ver. 0.01 initial create (empty) 18-Apr-2014 			 Initials (eg. JB)

clear;
close all;
clc;

%%%%%%%%%%%%%%----Nicht-so-wichtig----%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Websites
% met.no: http://api.met.no/weatherapi/locationforecast/1.8/?lat=53.143889;lon=8.213889
%
% wonderground.com: http://api.wunderground.com/api/a6e1ba8ffec4fb4a/forecast10day/q/Germany/Oldenburg.json
% API-Key-Franzus: a6e1ba8ffec4fb4a
%
% path_met_xml = urlwrite('http://api.met.no/weatherapi/locationforecast/1.8/?lat=53.143889;lon=8.213889', 'weather_met.xml');
%
% path_wg_xml = urlwrite('http://api.wunderground.com/api/a6e1ba8ffec4fb4a/forecast10day/q/Germany/Oldenburg.xml','weather_wg.xml');
% path_wg_json = urlwrite('http://api.wunderground.com/api/a6e1ba8ffec4fb4a/forecast10day/q/Germany/Oldenburg.json','weather_wg.json');
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


daystruct = WetterDatenVerarbeitung();

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% GUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUIGUI %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


hfig = figure();

set(hfig,'units','normalized',...
         'position', [0 0 1 1],...
         'ToolBar','none',...
         'Color',[1 1 0.7],...
         'MenuBar','none');

%-----------------Einbinden Update-Button--------------------

weatherupdate_control = uicontrol(hfig,'style', 'pushbutton',...
                                'units','normalized',...
                                'position',[0.35 0.1 0.3 0.1],...
                                'BackgroundColor',[1 0.8 0.4],...
                                'string','update weatherdata');
                            
% -----------------Einbinden der Uberschrift ----------------------------

title_text_control = uicontrol(hfig,'style','text',...
                                'units', 'normalized',...
                                'position',   [0.4 0.87 0.2 0.1],...
                                'string', 'Weather Forecast Oldenburg',...
                                'FontUnits','normalized',...
                                'FontSize',0.3,...
                                'BackgroundColor', [1 1 0.7]);                     

%--- Einbinden des Startdatums sowie Enddatums der Wettervorhersage-------
                            
x_pos_date = 0.02;
y_pos_date = 0.8;
x_size_date = 0.2;
y_size_date = 0.03;
x_distance_date = 0.01;
y_distance_date = 0.01;
                            
startdate_text_control = uicontrol(hfig,'style', 'text',...
                                'units','normalized',...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_date (y_pos_date + (y_size_date + y_distance_date)) x_size_date y_size_date],...
                                'string','startdate:');              


enddate_text_control = uicontrol(hfig,'style', 'text',...
                                'units','normalized',...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_date + (x_size_date + x_distance_date) y_pos_date + (y_size_date + y_distance_date), x_size_date y_size_date],...
                                'string','enddate:'); 
                            
startdate_popup_control = uicontrol(hfig,'style', 'popupmenu',...
                                'units','normalized',...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_date y_pos_date x_size_date y_size_date],...
                                'string',{daystruct(1).date,...
                                daystruct(2).date, daystruct(3).date, daystruct(4).date...
                                daystruct(5).date, daystruct(6).date, daystruct(7).date});
                           
enddate_popup_control = uicontrol(hfig, 'style', 'popupmenu',...
                                'units', 'normalized',...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position', [x_pos_date + (x_size_date + x_distance_date) y_pos_date x_size_date y_size_date],...
                                'string', {daystruct(1).date,...
                                daystruct(2).date, daystruct(3).date,daystruct(4).date...
                                daystruct(5).date, daystruct(6).date,daystruct(7).date});
                            
%-------------- Einbinden der Checkboxen  -------------------------------

weather_components = fieldnames(daystruct);

x_pos_checkbox = 0.8;
y_pos_checkbox = 0.8;
x_size_checkbox = 0.2;
y_size_checkbox = 0.02;

y_distance_checkbox = 0.01;

%{ 
weathercomponents_text_control = uicontrol(hfig,'style', 'text',...
                                'units','normalized',...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_checkbox (y_pos_checkbox+(y_size_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string','weather components:'); 

precipitation_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox y_pos_checkbox x_size_checkbox y_size_checkbox],...
                                'string', weather_components{2});


temp_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{3});
                            

winddir_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-2*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{4});
                            

                            
windspeed_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-3*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{5});
                            

humidity_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-4*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{6});
                            

pressure_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-5*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{7});
                            

cloudiness_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-6*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{8});
                            

fog_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-7*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{9});
                            

lowclouds_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-8*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{10});
                            

medclouds_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-9*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{11});
                            

highclouds_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-10*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{12});
                            

dptemp_checkbox_control = uicontrol(hfig, 'style', 'checkbox',...
                                'units', 'normalized',...
                                'position', [x_pos_checkbox (y_pos_checkbox-11*(y_distance_checkbox + y_size_checkbox))...
                                x_size_checkbox y_size_checkbox],...
                                'string', weather_components{13});
                            
%}                            
%---------------Einbinden Plot-Panel--------------------------------------

plot_control = uipanel('Parent', hfig,...
             'units', 'normalized',...
             'ShadowColor',[1 1 0.7],...
             'BackgroundColor',[1 1 0.7],...
             'position',   [0.02 0.25 (1 - 2*0.02) 0.5]);

day_panel_number = 3;

x_dis_day_pan = 0;
y_dis_day_pan = 0;
x_size_day_pan = (1-(2*x_dis_day_pan))/day_panel_number ;
y_size_day_pan = 1 - 2*y_dis_day_pan;

x_pos_daytime_pan = 0;
% y_pos_midnight_pan = 0.75;
y_pos_morning_pan = 0.67;
y_pos_midday_pan = 0.34;
y_pos_evening_pan = 0;
x_size_daytime_pan = 1;
y_size_daytime_pan = 0.33;

degree_symbol = sprintf('%c', char(176));


for pan_idx = 1:day_panel_number
    
    day_panel_control = uipanel('Parent', plot_control,...
                            'units', 'normalized',...
                            'Title', daystruct(pan_idx).date,...
                            'TitlePosition', 'centertop',...
                            'FontUnits','normalized',...
                            'FontSize',0.05,...
                            'FontWeight', 'bold',...
                            'ShadowColor',[1 1 0.7],...
                            'BackgroundColor',[1 1 0.7],...
                            'position',[x_dis_day_pan + (pan_idx-1)*(x_size_day_pan),...
                            y_dis_day_pan, x_size_day_pan, y_size_day_pan]);
                        
%-----------midnight-panel----------------------------------------------- 

%     midnight_panel_control = uipanel('Parent', day_panel_control,...
%                             'units', 'normalized',...
%                             'Title','Midnight:',...
%                             'TitlePosition', 'lefttop',...
%                             'FontUnits','normalized',...
%                             'FontSize',0.15,...
%                             'BackgroundColor',[1 1 0.7],...
%                             'position', [x_pos_daytime_pan, y_pos_midnight_pan,...
%                             x_size_daytime_pan, y_size_daytime_pan]);
%                         
%     midnight_picture_weather = axes('Parent', midnight_panel_control,...
%                             'Units','normalized',...
%                             'Box','Off',...
%                             'Position',[0 0.4 0.5 0.5]);          
%                             axes(midnight_picture_weather);
%                             image(daystruct(pan_idx).picture.midnight);
%                             axis image  
%                             axis off
%                 
%     midnight_temp_text_control = uicontrol('Parent', midnight_panel_control,...
%                             'style','text',...
%                             'units', 'normalized',...
%                             'FontUnits','normalized',...
%                             'FontSize',0.8,...
%                             'position',   [0.5 0.5 0.5 0.5],...
%                             'BackgroundColor', [1 1 0.7],...
%                             'string',  horzcat('22',degree_symbol));
%                            
%    midnight_percipitation_text_control = uicontrol('Parent', midnight_panel_control,...
%                             'style','text',...
%                             'FontUnits','normalized',...
%                             'FontSize',0.8,...
%                             'units', 'normalized',...
%                             'position',   [0 0.16 0.5 0.2],...
%                             'BackgroundColor', [1 1 0.7],...
%                             'string',  horzcat('percipitation: 0.1 mm '));
%                             
  %-----------------morning- panel---------------------------------------
  
   morning_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Morning:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize',0.15,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_morning_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);
    

                        
if isa(daystruct(pan_idx).temperature.morning,'double') == 1
    
     morning_NA_text_control = uicontrol('Parent', morning_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.3,...
                            'position',   [0.05 0.2 0.9 0.6],...
                            'BackgroundColor', [1 1 0.7],...
                            'string', 'weatherdata n.a.');

elseif isa(daystruct(pan_idx).temperature.morning,'double') == 0
                        
    morning_picture_weather = axes('Parent', morning_panel_control,...
                            'Units','normalized',...
                            'Box','Off',...
                            'Position',[0 0.4 0.5 0.5]);          
                            axes(morning_picture_weather);
                            image(daystruct(pan_idx).picture.morning);
                            axis image  
                            axis off
                
    morning_temp_text_control = uicontrol('Parent', morning_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.7,...
                            'position',   [0.4 0.4 0.6 0.5],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat(daystruct(pan_idx).temperature.morning.value,...
                            degree_symbol, 'C'));
                           
   morning_precipitation_text_control = uicontrol('Parent', morning_panel_control,...
                            'style','text',...
                            'FontUnits','normalized',...
                            'FontSize',0.8,...
                            'units', 'normalized',...
                            'position',   [0 0.16 1 0.2],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat('precipitation: ',...
                            daystruct(pan_idx).precipitation.morning.value, char(12),...
                            daystruct(pan_idx).precipitation.morning.unit));
end

%------midday-panel-----------------------------------------

midday_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Midday:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize',0.15,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_midday_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);

if isa(daystruct(pan_idx).temperature.midday,'double') == 1
    
     midday_NA_text_control = uicontrol('Parent', midday_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.3,...
                            'position',   [0.05 0.2 0.9 0.6],...
                            'BackgroundColor', [1 1 0.7],...
                            'string', 'weatherdata n.a.');


elseif isa(daystruct(pan_idx).temperature.midday,'double') == 0


                        
    midday_picture_weather = axes('Parent', midday_panel_control,...
                            'Units','normalized',...
                            'Box','Off',...
                            'Position',[0 0.4 0.5 0.5]);          
                            axes(midday_picture_weather);
                            image(daystruct(pan_idx).picture.midday);
                            axis image  
                            axis off
                
    midday_temp_text_control = uicontrol('Parent', midday_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.7,...
                            'position',   [0.4 0.4 0.6 0.5],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat(daystruct(pan_idx).temperature.midday.value,...
                            degree_symbol, 'C'));
                           
   midday_precipitation_text_control = uicontrol('Parent', midday_panel_control,...
                            'style','text',...
                            'FontUnits','normalized',...
                            'FontSize',0.8,...
                            'units', 'normalized',...
                            'position',   [0 0.16 1 0.2],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat('precipitation: ',...
                            daystruct(pan_idx).precipitation.midday.value, char(12),...
                            daystruct(pan_idx).precipitation.midday.unit)); 
end

%---------evening-panel-----------------------------------------------------

evening_panel_control = uipanel('Parent', day_panel_control,...
                            'units', 'normalized',...
                            'Title','Evening:',...
                            'TitlePosition', 'lefttop',...
                            'FontUnits','normalized',...
                            'FontSize',0.15,...
                            'BackgroundColor',[1 1 0.7],...
                            'position', [x_pos_daytime_pan, y_pos_evening_pan,...
                            x_size_daytime_pan, y_size_daytime_pan]);

if isa(daystruct(pan_idx).temperature.evening,'double') == 1
    
     morning_NA_text_control = uicontrol('Parent', evening_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.3,...
                            'position',   [0.05 0.2 0.9 0.6],...
                            'BackgroundColor', [1 1 0.7],...
                            'string', 'weatherdata n.a.');

elseif isa(daystruct(pan_idx).temperature.evening,'double') == 0
    
                        
    evening_picture_weather = axes('Parent', evening_panel_control,...
                            'Units','normalized',...
                            'Box','Off',...
                            'Position',[0 0.4 0.5 0.5]);          
                            axes(evening_picture_weather);
                            image(daystruct(pan_idx).picture.evening);
                            axis image  
                            axis off

    evening_temp_text_control = uicontrol('Parent', evening_panel_control,...
                            'style','text',...
                            'units', 'normalized',...
                            'FontUnits','normalized',...
                            'FontSize',0.7,...
                            'position',   [0.4 0.4 0.6 0.5],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat(daystruct(pan_idx).temperature.evening.value,...
                            degree_symbol, 'C'));
                           
   evening_precipitation_text_control = uicontrol('Parent', evening_panel_control,...
                            'style','text',...
                            'FontUnits','normalized',...
                            'FontSize',0.8,...
                            'units', 'normalized',...
                            'position',   [0 0.16 1 0.2],...
                            'BackgroundColor', [1 1 0.7],...
                            'string',  horzcat('precipitation: ',...
                            daystruct(pan_idx).precipitation.evening.value,...
                            char(12), daystruct(pan_idx).precipitation.evening.unit)); 

end
end
                                                
                       
    
                        
                            
                            
%--------------------Licence ---------------------------------------------
% Copyright (c) <2014> L. Hartog, F. Wichert
% Institute for Hearing Technology and Audiology
% Jade University of Applied Sciences 
% Permission is hereby granted, free of charge, to any person obtaining 
% a copy of this software and associated documentation files 
% (the "Software"), to deal in the Software without restriction, including 
% without limitation the rights to use, copy, modify, merge, publish, 
% distribute, sublicense, and/or sell copies of the Software, and to
% permit persons to whom the Software is furnished to do so, subject
% to the following conditions:
% The above copyright notice and this permission notice shall be included 
% in all copies or substantial portions of the Software.
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
% EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
% OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
% IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
% CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
% TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
% SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.