% mainscript for the project "weatherforecast Oldenburg"
% This script opens a GUI with which it is able to show the weatherforecast
% for the place "Oldenburg" for maximum 7 days.
%
% Copyright 2014 Laura Hartog, Franz Wichert

clear;
close all;
clc;

daystruct = weather_data_reprocessing();

hfig = figure();

set(hfig,'units','normalized',...
         'tag','mainfig',...
         'name', 'Weather Forecast Oldenburg',...
         'position', [0 0 1 1],...
         'ToolBar','none',...
         'Color',[1 1 0.7],...
         'MenuBar','none');


%------------------------Including of headline----------------------------%

title_text_control = uicontrol(hfig,'style','text',...
                                'units', 'normalized',...
                                'position',   [0.38 0.87 0.3 0.1],...
                                'string', 'Weather Forecast Oldenburg',...
                                'FontUnits','normalized',...
                                'FontSize',0.43,...
                                'BackgroundColor', [1 1 0.7]);                     
                            
%------Including of startdate- and enddate-popup of weatherforecast-------%
                            
x_pos_date = 0.02;
y_pos_date = 0.8;
x_size_date = 0.18;
y_size_date = 0.03;
x_distance_date = 0.01;
y_distance_date = 0.01;
date_text_size = 0.9;
date_popup_size = 0.7;

startdate_text_control = uicontrol(hfig,'style', 'text',...
                                'units','normalized',...
                                'BackgroundColor',[1 0.8 0.4],...
                                'FontUnits','normalized',...
                                'Fontsize', date_text_size,...
                                'position',[x_pos_date (y_pos_date + (y_size_date + y_distance_date))...
                                x_size_date y_size_date],...
                                'string','startdate:');              


enddate_text_control = uicontrol(hfig,'style', 'text',...
                                'units','normalized',...
                                'FontUnits','normalized',...
                                'Fontsize', date_text_size,...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_date + (x_size_date + x_distance_date) y_pos_date + (y_size_date + y_distance_date), x_size_date y_size_date],...
                                'string','enddate:'); 
                            
startdate_popup_control = uicontrol(hfig,'style', 'popupmenu',...
                                'tag','startdate_popup',...
                                'units','normalized',...
                                'FontUnits','normalized',...
                                'Fontsize', date_popup_size,...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position',[x_pos_date y_pos_date x_size_date y_size_date],...
                                'string',{daystruct(1).date,...
                                daystruct(2).date, daystruct(3).date, daystruct(4).date...
                                daystruct(5).date, daystruct(6).date, daystruct(7).date},...
                                 'callback',@Error_window_fcn);
                           
enddate_popup_control = uicontrol(hfig, 'style', 'popupmenu',...
                                'tag','enddate_popup',...
                                'units', 'normalized',...
                                'FontUnits','normalized',...
                                'Fontsize', date_popup_size,...
                                'BackgroundColor',[1 0.8 0.4],...
                                'position', [x_pos_date + (x_size_date + x_distance_date) y_pos_date x_size_date y_size_date],...
                                'string', {daystruct(1).date,...
                                daystruct(2).date, daystruct(3).date,daystruct(4).date...
                                daystruct(5).date, daystruct(6).date,daystruct(7).date},...
                                'callback',@Error_window_fcn);


%-----------------------Including of update-button------------------------%

weatherupdate_control = uicontrol(hfig,'style', 'pushbutton',...
                                'tag','weatherupdate_push',...
                                'units','normalized',...
                                'position',[0.7 0.79 0.28 0.08],...
                                'BackgroundColor',[1 0.8 0.4],...
                                'FontUnits','normalized',...
                                'FontSize',0.3,...
                                'string','show weatherforecast',...
                                'callback', {@update_plot_fcn, daystruct});


                            
                            
                            
                            
%------------------------Generating GUI handle-struct---------------------%
data = guihandles(hfig);
guidata(hfig, data);